# Iterating over multiple refutation tests
The objective of this notebook is to compare the ability of refuters to detect the problems in a given set of estimators.
Note:
This notebook makes use of the optional dependencies:
- pygraphviz
- causalml

## Import Dependencies

In [1]:
from dowhy.datasets import linear_dataset
from dowhy import CausalModel
import causalml

# Config dict to set the logging level
import logging.config
DEFAULT_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        '': {
            'level': 'WARN',
        },
    }
}

logging.config.dictConfig(DEFAULT_LOGGING)
# Disabling warnings output
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

## Inspection Parameters
These parameters give us the option of inspecting the intermediate steps to sanity check the steps performed

In [2]:
inspect_datasets = True
inspect_models = True
inspect_identified_estimands = True
inspect_estimates = True
inspect_refutations = True

## Estimator List
We pass a list of strings, corresponding to the estimators of interest

In [3]:
estimator_list = ["backdoor.propensity_score_matching", "backdoor.propensity_score_weighting", "backdoor.causalml.inference.meta.LRSRegressor"]
method_params= [ None, None, { "init_params":{} } ]

## Refuter List
A list of strings, corresponding to each refuter we wish to run

In [4]:
refuter_list = ["bootstrap_refuter", "data_subset_refuter"]

## Create the Datasets

In [5]:
# Parameters for creating the Dataset
TREATMENT_IS_BINARY = True
BETA = 10
NUM_SAMPLES = 5000
NUM_CONFOUNDERS = 5
NUM_INSTRUMENTS = 3
NUM_EFFECT_MODIFIERS = 2

# Creating a Linear Dataset with the given parameters
linear_data = linear_dataset(
            beta = BETA,
            num_common_causes = NUM_CONFOUNDERS,
            num_instruments = NUM_INSTRUMENTS,
            num_effect_modifiers = NUM_EFFECT_MODIFIERS,
            num_samples = NUM_SAMPLES,
            treatment_is_binary = True
        )
# Other datasets come here 


# Append them together in an array
datasets = [linear_data]

## Inspect Data

In [6]:
dataset_num = 1
if inspect_datasets is True:
    for data in datasets:
        print("####### Dataset {}###########################################################################################".format(dataset_num))
        print(data['df'].head())
        print("#############################################################################################################")
        dataset_num += 1

####### Dataset 1###########################################################################################
         X0        X1   Z0        Z1   Z2        W0        W1        W2  \
0  0.815561  1.382192  0.0  0.032699  0.0 -0.349572 -1.011814 -1.409937
1  0.565588 -0.121230  0.0  0.191581  0.0  1.500906 -1.133247 -1.990940
2  0.641187 -0.785662  1.0  0.959832  0.0  0.172375  0.482692 -2.712835
3  0.076662  1.159605  0.0  0.428127  0.0  2.273463  0.327248  1.290102
4  0.861989  0.494334  0.0  0.553362  0.0  0.904391  0.469244  0.403471

         W3        W4     v0          y
0 -0.294557 -1.073794  False  -7.431833
1  0.572827  0.111985   True  10.881939
2  0.575473  0.166511   True  14.268640
3  0.401685 -0.335078   True  18.930332
4  1.122946  1.625132   True  21.673668
#############################################################################################################

## Create the CausalModels

In [7]:
models = []
for data in datasets:
    model = CausalModel(
                data = data['df'],
                treatment = data['treatment_name'],
                outcome = data['outcome_name'],
                graph = data['gml_graph']
            )
    models.append(model)

## Inspect Models

In [8]:
model_num = 1
if inspect_models is True:
    for model in models:
        print("####### Model {}#############################################################################################".format(model_num))
        print("Common Causes:",model._common_causes)
        print("Effect Modifiers:",model._effect_modifiers)
        print("Instruments:",model._instruments)
        print("Outcome:",model._outcome)
        print("Treatment:",model._treatment)
        print("#############################################################################################################")
        model_num += 1

####### Model 1#############################################################################################
Common Causes: ['Unobserved Confounders', 'W2', 'W4', 'W3', 'W1', 'W0']
Effect Modifiers: ['X1', 'X0']
Instruments: ['Z1', 'Z2', 'Z0']
Outcome: ['y']
Treatment: ['v0']
#############################################################################################################

## Identify Effect

In [9]:
identified_estimands = []
for model in models:
    identified_estimand = model.identify_effect(proceed_when_unidentifiable=True)
    identified_estimands.append(identified_estimand)

## Identified Estimands

In [10]:
estimand_count = 1
for estimand in identified_estimands:
    print("####### Identified Estimand {}#####################################################################################".format(estimand_count))
    print(estimand)
    print("###################################################################################################################")
    estimand_count += 1

####### Identified Estimand 1#####################################################################################
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
  d
─────(Expectation(y|W2,W4,W3,W1,X1,W0,X0))
d[v₀]
Estimand assumption 1, Unconfoundedness: If U→{v0} and U→y then P(y|v0,W2,W4,W3,W1,X1,W0,X0,U) = P(y|v0,W2,W4,W3,W1,X1,W0,X0)

### Estimand : 2
Estimand name: iv
Estimand expression:
Expectation(Derivative(y, [Z1, Z2, Z0])*Derivative([v0], [Z1, Z2, Z0])**(-1))
Estimand assumption 1, As-if-random: If U→→y then ¬(U →→{Z1,Z2,Z0})
Estimand assumption 2, Exclusion: If we remove {Z1,Z2,Z0}→{v0}, then ¬({Z1,Z2,Z0}→y)

### Estimand : 3
Estimand name: frontdoor
No such variable found!

###################################################################################################################

## Estimate Effect

In [11]:
estimate_list = []
for i in range(len(identified_estimands)):
    for j in range(len(estimator_list)):
        estimate = model.estimate_effect(
                        identified_estimands[i],
                        method_name=estimator_list[j],
                        method_params=method_params[j]
                  )
        estimate_list.append(estimate)

/home/amit/py-envs/env3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/home/amit/py-envs/env3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

{'X':             W2        W4        W3        W1        X1        W0        X0  \
0    -1.409937 -1.073794 -0.294557 -1.011814  1.382192 -0.349572  0.815561
1    -1.990940  0.111985  0.572827 -1.133247 -0.121230  1.500906  0.565588
2    -2.712835  0.166511  0.575473  0.482692 -0.785662  0.172375  0.641187
3     1.290102 -0.335078  0.401685  0.327248  1.159605  2.273463  0.076662
4     0.403471  1.625132  1.122946  0.469244  0.494334  0.904391  0.861989
...        ...       ...       ...       ...       ...       ...       ...
4995 -1.523082  2.356658 -1.326664  0.655229  1.413582  2.273291  0.934879
4996 -1.116186 -0.792025 -0.800518  0.969778  1.004574  1.004584 -1.038316
4997 -1.052103  0.112904  0.015627 -1.293327  0.701666  1.729135  0.214009
4998  0.671167  1.218955  0.577825  0.073284 -1.145990  0.997583  0.831404
4999 -1.667117 -0.272001  0.464098  0.107621 -1.471820  1.069207  0.122401

            X1        X0
0     1.382192  0.815561
1    -0.121230  0.565588
2    -0.785662  0.641187
3     1.159605  0.076662
4     0.494334  0.861989
...        ...       ...
4995  1.413582  0.934879
4996  1.004574 -1.038316
4997  0.701666  0.214009
4998 -1.145990  0.831404
4999 -1.471820  0.122401

[5000 rows x 9 columns], 'y': 0       -7.431833
1       10.881939
2       14.268640
3       18.930332
4       21.673668
          ...
4995    10.630741
4996    12.751352
4997    10.265862
4998    16.215069
4999    11.069029
Name: y, Length: 5000, dtype: float64, 'treatment': 0       False
1        True
2        True
3        True
4        True
        ...
4995    False
4996     True
4997     True
4998     True
4999     True
Name: v0, Length: 5000, dtype: bool}

## Estimate Values

In [12]:
estimand_count = 1
if inspect_estimates is True:
    for estimand in estimate_list:
        print("####### Estimand {}#######################################################################################".format(estimand_count))
        print("*** Class Name ***")
        print()
        print(estimand.params['estimator_class'])
        print()
        print(estimand)
        print("########################################################################################################")
        print()
        estimand_count += 1

####### Estimand 1#######################################################################################
*** Class Name ***

<class 'dowhy.causal_estimators.propensity_score_matching_estimator.PropensityScoreMatchingEstimator'>

*** Causal Estimate ***

## Identified estimand
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
  d
─────(Expectation(y|W2,W4,W3,W1,X1,W0,X0))
d[v₀]
Estimand assumption 1, Unconfoundedness: If U→{v0} and U→y then P(y|v0,W2,W4,W3,W1,X1,W0,X0,U) = P(y|v0,W2,W4,W3,W1,X1,W0,X0)

## Realized estimand
b: y~v0+W2+W4+W3+W1+X1+W0+X0
Target units: ate

## Estimate
Mean value: 13.879166147783451

########################################################################################################

####### Estimand 2#######################################################################################
*** Class Name ***

<class 'dowhy.causal_estimators.propensity_score_weighting_estimator.PropensityScoreWeightingEstimator'>

*** Causal Estimate ***

## Identified estimand
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
  d
─────(Expectation(y|W2,W4,W3,W1,X1,W0,X0))
d[v₀]
Estimand assumption 1, Unconfoundedness: If U→{v0} and U→y then P(y|v0,W2,W4,W3,W1,X1,W0,X0,U) = P(y|v0,W2,W4,W3,W1,X1,W0,X0)

## Realized estimand
b: y~v0+W2+W4+W3+W1+X1+W0+X0
Target units: ate

## Estimate
Mean value: 14.961425818165385

########################################################################################################

####### Estimand 3#######################################################################################
*** Class Name ***

<class 'dowhy.causal_estimators.causalml.Causalml'>

*** Causal Estimate ***

## Identified estimand
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
  d
─────(Expectation(y|W2,W4,W3,W1,X1,W0,X0))
d[v₀]
Estimand assumption 1, Unconfoundedness: If U→{v0} and U→y then P(y|v0,W2,W4,W3,W1,X1,W0,X0,U) = P(y|v0,W2,W4,W3,W1,X1,W0,X0)

## Realized estimand
b: y~v0+W2+W4+W3+W1+X1+W0+X0
Target units: ate

## Estimate
Mean value: [12.82779527]
Effect estimates: [[12.82779527]
 [12.82779527]
 [12.82779527]
 ...
 [12.82779527]
 [12.82779527]
 [12.82779527]]

########################################################################################################

## Refute Estimate

In [13]:
refutation_list = []
for estimand in identified_estimands:
    for estimate in estimate_list: 
        for refuter in refuter_list:
            ref = model.refute_estimate(estimand, estimate,method_name=refuter)
            refutation_list.append(ref)

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

{'X':             W2        W4        W3        W1        X1        W0        X0  \
93   -1.128470  0.803796 -0.849364  0.266145 -0.898931  1.769310  0.072095
1088  0.002826  1.175457 -0.165811 -1.036364  1.492922  1.770450  1.134532
2172 -0.340529  1.923116  2.123854 -1.499390 -1.321158  0.995319 -0.686868
3285 -0.486722  1.118134  1.452272 -0.987275  0.016285  0.150814  0.190272
1057 -0.426275 -0.112688  0.936973  0.997815 -1.062028  1.102444  2.198371
...        ...       ...       ...       ...       ...       ...       ...
4823 -0.720302  0.888529  0.723755 -1.820770 -0.491517  1.266704 -0.325428
3292 -1.883412  1.381702  0.630555  0.523012  0.600994  1.470406  1.104361
1444 -1.077868 -0.810679  0.525418 -0.806209 -1.114339  0.198871  0.831400
236  -0.951846 -0.671687  0.649086 -0.822443  1.232260  0.638697  0.966714
239  -1.521737 -0.147820 -1.469830 -1.244154  1.264690  0.450694 -0.536106

            X1        X0
93   -0.898931  0.072095
1088  1.492922  1.134532
2172 -1.321158 -0.686868
3285  0.016285  0.190272
1057 -1.062028  2.198371
...        ...       ...
4823 -0.491517 -0.325428
3292  0.600994  1.104361
1444 -1.114339  0.831400
236   1.232260  0.966714
239   1.264690 -0.536106

[5000 rows x 9 columns], 'y': 93      14.002035
1088    18.198535
2172     7.071185
3285     9.938453
1057    23.233456
          ...
4823     4.814064
3292    22.584796
1444     7.744684
236     10.675933
239     -5.674551
Name: y, Length: 5000, dtype: float64, 'treatment': 93       True
1088     True
2172     True
3285     True
1057     True
        ...
4823     True
3292     True
1444     True
236      True
239     False
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
3766  0.705785  0.519483  0.373609 -0.382871  0.940863  0.572413 -0.137014
1937 -0.927061  0.260515  1.949281 -0.826676  2.047490  1.082525 -0.552054
4521 -1.280717  1.573800  1.455551 -0.517148  1.354690  1.301090 -0.405578
2910  0.802627 -0.593973  0.066746 -0.847901  0.956710  0.489640 -0.719291
2089 -0.186005  1.435422 -1.493089 -1.310541  0.544113  2.001583  0.953466
...        ...       ...       ...       ...       ...       ...       ...
2621 -0.771403 -1.364822  0.818501 -0.352753  1.347089  0.241284 -1.330746
2837 -1.286418  0.852655 -0.573994 -1.156086  2.595357 -0.045077  2.754514
2562 -0.588970 -0.087310  1.449469 -0.864397  1.899294  2.735263  0.515756
252   0.905816  1.559438  0.852178 -1.485987 -1.072765  0.958362  0.645487
2917  0.039117 -1.094309  1.054458 -2.824041  0.345335 -1.323637 -0.383539

            X1        X0
3766  0.940863 -0.137014
1937  2.047490 -0.552054
4521  1.354690 -0.405578
2910  0.956710 -0.719291
2089  0.544113  0.953466
...        ...       ...
2621  1.347089 -1.330746
2837  2.595357  2.754514
2562  1.899294  0.515756
252  -1.072765  0.645487
2917  0.345335 -0.383539

[5000 rows x 9 columns], 'y': 3766    11.987051
1937    11.837503
4521    16.144046
2910     6.598981
2089    13.085114
          ...
2621     5.696583
2837    17.576338
2562    18.838240
252     11.018144
2917   -17.048424
Name: y, Length: 5000, dtype: float64, 'treatment': 3766     True
1937     True
4521     True
2910     True
2089     True
        ...
2621     True
2837     True
2562     True
252      True
2917    False
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
3120  0.030133 -1.578504  1.107558 -1.063730  0.449537  0.710989  1.174442
2744  1.110717  1.080912  1.269319 -0.392650  0.557287  0.372931  1.556674
3145  0.093074 -1.462376  0.907807  0.308703 -1.720340  1.076785 -1.509002
2666 -1.720909 -0.880539  0.453326 -0.640901 -1.192202  0.164446 -0.393032
4539 -0.076548 -1.000856 -0.782063  0.897225  0.221707  2.243186  3.138771
...        ...       ...       ...       ...       ...       ...       ...
1570 -0.065932 -0.771146  1.365195 -0.379087 -2.700320  2.311231  1.361967
877  -0.460566 -0.150479  1.189769 -0.833921 -0.784373  3.106751 -0.699459
3739 -1.392188 -0.902102 -0.603839 -1.730818  2.358897  1.485747  1.427637
3265 -3.583440 -0.207926 -1.251573 -1.921912  1.122571 -0.622592  0.065013
220  -0.250070  1.078181 -0.679491 -2.057915  1.274275 -0.309054  2.202287

            X1        X0
3120  0.449537  1.174442
2744  0.557287  1.556674
3145 -1.720340 -1.509002
2666 -1.192202 -0.393032
4539  0.221707  3.138771
...        ...       ...
1570 -2.700320  1.361967
877  -0.784373 -0.699459
3739  2.358897  1.427637
3265  1.122571  0.065013
220   1.274275  2.202287

[5000 rows x 9 columns], 'y': 3120     9.205212
2744    17.458570
3145     4.653603
2666     3.138149
4539    27.484782
          ...
1570    14.334940
877     10.457742
3739    11.217661
3265   -11.955311
220     -8.826730
Name: y, Length: 5000, dtype: float64, 'treatment': 3120     True
2744     True
3145     True
2666     True
4539     True
        ...
1570     True
877      True
3739     True
3265    False
220     False
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
2661 -1.280735 -1.099812  1.356750  0.321320  0.437382  1.220247 -1.256277
355  -0.705903  0.261021  1.627123  0.478537  0.677975  1.049893 -0.564608
4767 -1.052029  1.568160  1.113557  0.036574  2.025595  1.979423 -0.549465
4912 -1.031257  0.466402  1.224127 -1.086360 -0.643689  2.057229  0.052169
3973 -1.291226 -0.702398  0.290860  0.889324  0.171737  0.893152  0.348044
...        ...       ...       ...       ...       ...       ...       ...
3760 -1.600854  1.264672  2.406585 -0.140576  0.612423  0.220596  0.571501
2976 -0.135394  1.033128  1.787401 -0.074463  0.800613  0.363257  0.414248
2795  0.070270  1.617862  2.020218 -0.366755  3.860018  1.202944  2.417506
2591 -1.636970  1.187440 -0.401007 -1.005131  0.939129  2.095031 -0.437921
3499  0.016486  0.394242 -1.204821 -0.921041  0.631624  0.382952  1.023271

            X1        X0
2661  0.437382 -1.256277
355   0.677975 -0.564608
4767  2.025595 -0.549465
4912 -0.643689  0.052169
3973  0.171737  0.348044
...        ...       ...
3760  0.612423  0.571501
2976  0.800613  0.414248
2795  3.860018  2.417506
2591  0.939129 -0.437921
3499  0.631624  1.023271

[5000 rows x 9 columns], 'y': 2661     8.514343
355     15.428098
4767    19.739730
4912    11.297899
3973    15.308959
          ...
3760    17.457258
2976    16.961689
2795    29.952978
2591    12.192883
3499    -3.942523
Name: y, Length: 5000, dtype: float64, 'treatment': 2661     True
355      True
4767     True
4912     True
3973     True
        ...
3760     True
2976     True
2795     True
2591     True
3499    False
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
4370  1.157675  1.047775  1.503989 -1.278366 -0.921367  2.548336  2.112991
4653 -1.061666 -0.125984  0.847355 -0.891992 -0.815047  1.907783  0.978523
1360 -0.052371  0.028751  0.145399 -2.014764 -1.332931 -0.165902 -0.658246
4256 -0.935048 -1.327718 -0.067095 -2.305079  0.100418  1.014158 -0.063243
239  -1.352514 -0.071005 -1.635634 -1.123763  1.304075  0.597451 -0.780659
...        ...       ...       ...       ...       ...       ...       ...
4704  0.489466 -0.499842  1.028875 -0.452220  0.099618 -0.099504  0.986054
2205  0.433751  0.648446  1.258696 -1.175802  2.307805  2.246515  1.612312
4820 -1.521765  1.652282  0.742704 -1.012177  1.409411  1.321403  1.021502
4381 -3.272863  0.968135  1.063820 -0.247689  1.521779  2.668159 -0.351991
2129 -0.981197 -1.270755  0.605028 -1.417201  0.653244  2.104788  1.253962

            X1        X0
4370 -0.921367  2.112991
4653 -0.815047  0.978523
1360 -1.332931 -0.658246
4256  0.100418 -0.063243
239   1.304075 -0.780659
...        ...       ...
4704  0.099618  0.986054
2205  2.307805  1.612312
4820  1.409411  1.021502
4381  1.521779 -0.351991
2129  0.653244  1.253962

[5000 rows x 9 columns], 'y': 4370    17.574201
4653    12.774998
1360    -8.815314
4256     0.386707
239     -5.674551
          ...
4704    11.024184
2205    21.501989
4820    16.897307
4381    18.934708
2129    13.294615
Name: y, Length: 5000, dtype: float64, 'treatment': 4370     True
4653     True
1360    False
4256     True
239     False
        ...
4704     True
2205     True
4820     True
4381     True
2129     True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
3782  0.168507  0.784798  1.189456 -0.780690  0.852463  0.216428  2.270378
4014 -2.556072  2.543305  1.101678 -0.244097  0.617215  1.379412 -0.093629
3128 -0.930958 -0.557656  0.764429 -0.311212  0.343489  0.909454  0.889444
4214 -1.930753  2.047628  0.029482 -0.214395  1.293378 -1.169465  1.730693
2830  0.130227 -0.875785  1.262717 -0.115966 -0.706258  0.016690  0.936511
...        ...       ...       ...       ...       ...       ...       ...
3756 -0.479228 -1.061039  0.714823  1.265491 -0.545748  0.301314  1.495825
4309  0.388822  1.216931 -0.049924  0.413226 -0.259610 -0.220817 -0.230637
2789 -1.230163  0.546514  3.397750 -1.636762 -0.189356 -0.061337 -1.070342
1017 -0.310646  0.061668 -0.903804 -0.279610  1.338362  0.914859 -0.442131
1561 -1.052630 -0.026267  0.705706 -0.166797  1.285767  0.389357  1.294604

            X1        X0
3782  0.852463  2.270378
4014  0.617215 -0.093629
3128  0.343489  0.889444
4214  1.293378  1.730693
2830 -0.706258  0.936511
...        ...       ...
3756 -0.545748  1.495825
4309 -0.259610 -0.230637
2789 -0.189356 -1.070342
1017  1.338362 -0.442131
1561  1.285767  1.294604

[5000 rows x 9 columns], 'y': 3782    16.909890
4014    18.943160
3128    14.664329
4214    16.995023
2830    10.928577
          ...
3756    20.607467
4309    12.462599
2789     4.578738
1017    10.354932
1561    17.282119
Name: y, Length: 5000, dtype: float64, 'treatment': 3782    True
4014    True
3128    True
4214    True
2830    True
        ...
3756    True
4309    True
2789    True
1017    True
1561    True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
1357 -1.506144  0.116137  0.042825 -0.855125  1.437920  0.504459  0.164544
3279 -2.574014  0.234049 -0.944398  0.056567 -1.348222  0.711985  1.128497
3255  0.562844  2.050778  0.454447 -0.353478  0.056660  0.857282  1.078617
3884 -0.213045  1.964856  1.376516 -1.621999  1.196721 -0.001195 -1.668212
3847 -0.278301 -0.416129  0.262667 -1.743448  2.655945  1.250056  0.139821
...        ...       ...       ...       ...       ...       ...       ...
1528 -0.009450  1.051223  1.138346 -2.338369 -0.664575 -0.044005  0.811306
320  -1.140332  0.507516 -1.459739 -1.148007  3.515834  1.429095  1.201401
3358 -0.974626 -0.274239 -0.530205 -1.956025  0.838270  2.896032 -0.379358
3779 -0.823650  0.853768  2.563799  0.798687  1.751411  0.432056 -0.002358
3815 -1.164638  1.583760  1.371598  0.835203 -0.190626 -0.163472 -0.669569

            X1        X0
1357  1.437920  0.164544
3279 -1.348222  1.128497
3255  0.056660  1.078617
3884  1.196721 -1.668212
3847  2.655945  0.139821
...        ...       ...
1528 -0.664575  0.811306
320   3.515834  1.201401
3358  0.838270 -0.379358
3779  1.751411 -0.002358
3815 -0.190626 -0.669569

[5000 rows x 9 columns], 'y': 1357    10.744280
3279    13.063425
3255    17.764606
3884     2.525731
3847     9.762767
          ...
1528     4.325575
320     17.191705
3358     6.887025
3779    21.342567
3815    14.766265
Name: y, Length: 5000, dtype: float64, 'treatment': 1357    True
3279    True
3255    True
3884    True
3847    True
        ...
1528    True
320     True
3358    True
3779    True
3815    True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
1565 -1.989112  0.105213 -0.176880  0.212156  1.539385 -0.038312  1.409801
459  -0.980685 -1.135691 -0.605145  1.674088  0.321524  1.730756 -0.004720
3557 -0.398518 -0.317816 -0.805104 -1.719579  0.742352  2.223729 -0.915839
716  -1.039316  1.067414  0.272723  0.091076  2.454732  1.584164 -1.459570
2587 -1.370915  0.946145  0.445298  0.317841 -0.166000  1.485238 -0.709976
...        ...       ...       ...       ...       ...       ...       ...
4347 -0.522554  0.258061 -0.240256  0.107483  0.973884  1.418282  1.024689
793  -1.186073  0.054422  1.716280 -1.157338 -0.659174  1.319532  1.461916
3291 -0.068218 -0.811883  0.509290 -0.256270  0.718146  0.311962  1.484380
3057 -1.125414  0.252365  2.536791 -1.115070 -1.493186  0.098063  0.241859
2747 -1.566687  0.181829  0.397848 -0.101460  2.331359  1.573884  0.941870

            X1        X0
1565  1.539385  1.409801
459   0.321524 -0.004720
3557  0.742352 -0.915839
716   2.454732 -1.459570
2587 -0.166000 -0.709976
...        ...       ...
4347  0.973884  1.024689
793  -0.659174  1.461916
3291  0.718146  1.484380
3057 -1.493186  0.241859
2747  2.331359  0.941870

[5000 rows x 9 columns], 'y': 1565    17.427760
459     18.163308
3557     4.023927
716     16.045114
2587    15.248328
          ...
4347    18.983305
793     14.091336
3291    14.691832
3057     6.739748
2747    21.166845
Name: y, Length: 5000, dtype: float64, 'treatment': 1565    True
459     True
3557    True
716     True
2587    True
        ...
4347    True
793     True
3291    True
3057    True
2747    True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
383  -1.286974 -0.372463  2.932323 -0.767047  0.397681  1.656389 -0.290523
4199  0.269021  0.296796  1.565655  0.309751  0.070115  1.211668  0.220631
4510  1.644293  0.872376  0.749273 -1.349053  0.582444  0.344411  0.257269
479  -0.617805 -0.075396  0.289749 -0.332058  1.573612  2.443023 -0.290991
2702  0.151187  1.018873 -1.636629  0.736300  2.050171  1.196173 -0.282112
...        ...       ...       ...       ...       ...       ...       ...
603   0.487941  0.847899 -0.263960 -1.252887  0.211043  0.715374  2.170682
3433  0.607471  0.313742  1.849009 -0.088169  2.096118 -0.498036  1.859756
1416 -2.235267  0.621489  0.998520 -0.667647  1.793226  1.177323  0.323835
910  -1.905988 -1.067448  1.032599 -0.109196  0.929290  0.561875  0.456066
4923 -0.138268  1.181532  0.768821 -1.094476 -0.055811  2.071905  1.430811

            X1        X0
383   0.397681 -0.290523
4199  0.070115  0.220631
4510  0.582444  0.257269
479   1.573612 -0.290991
2702  2.050171 -0.282112
...        ...       ...
603   0.211043  2.170682
3433  2.096118  1.859756
1416  1.793226  0.323835
910   0.929290  0.456066
4923 -0.055811  1.430811

[5000 rows x 9 columns], 'y': 383     13.349812
4199    17.787719
4510     7.571562
479     16.104166
2702    16.544561
          ...
603     15.581367
3433    20.266489
1416    15.631333
910     13.288728
4923    16.992181
Name: y, Length: 5000, dtype: float64, 'treatment': 383     True
4199    True
4510    True
479     True
2702    True
        ...
603     True
3433    True
1416    True
910     True
4923    True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
2300 -1.653093  0.155700  1.327860  0.226367  2.809622  2.118115 -0.398980
4472 -1.607231 -0.235052  0.193346 -1.482222  1.639041  1.920355 -0.799748
2201 -0.094492 -0.021788 -0.591926  0.084402  0.610917 -0.224670  0.222871
2843 -0.434994 -0.617562  0.625702 -1.319879  0.119611 -0.152893  0.015220
3005 -2.315495  0.118668  0.898099 -2.405266  0.808132  2.199287  2.152571
...        ...       ...       ...       ...       ...       ...       ...
21   -1.159716  0.235530 -1.089874 -1.063745  0.476939  0.099472  0.817196
1361 -0.118673  0.357555  1.077620 -0.739742  0.061622  2.737252  1.708118
2166 -2.022931  0.464688  0.579496 -3.184107  0.892448  0.743854  1.479010
4189  1.665161 -0.225402  2.512350 -1.081180  0.956947  2.081235 -0.624452
96   -1.117022  1.035830  1.851383 -2.680069  1.337400  0.725619  1.467628

            X1        X0
2300  2.809622 -0.398980
4472  1.639041 -0.799748
2201  0.610917  0.222871
2843  0.119611  0.015220
3005  0.808132  2.152571
...        ...       ...
21    0.476939  0.817196
1361  0.061622  1.708118
2166  0.892448  1.479010
4189  0.956947 -0.624452
96    1.337400  1.467628

[5000 rows x 9 columns], 'y': 2300    21.309708
4472     6.395279
2201    11.093757
2843     3.776703
3005    15.157312
          ...
21       9.504391
1361    20.564008
2166   -11.396504
4189    11.079678
96       8.941384
Name: y, Length: 5000, dtype: float64, 'treatment': 2300     True
4472     True
2201     True
2843     True
3005     True
        ...
21       True
1361     True
2166    False
4189     True
96       True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
1107 -2.780193  0.160977  0.638425  0.983314  3.069596 -0.463237  1.984833
1468  1.447252 -0.745139 -0.131472 -2.038083  0.167195  1.105965  0.234812
123  -0.750369  2.278511 -1.006722 -2.180406  1.545630  1.594916 -0.318047
523  -2.429111  0.206104 -0.224054  0.041810 -1.570886 -0.362121 -0.397793
4566 -0.645624  0.922682  1.309860 -0.069103  0.831990 -0.630603 -0.144920
...        ...       ...       ...       ...       ...       ...       ...
4681 -1.635793  0.782015 -0.902642 -2.284160  0.788349 -0.077957  0.246560
3369 -1.451558  1.094535  1.115966  1.394476 -0.115708  1.956958  1.480462
4280 -0.769388 -0.232602 -0.585198 -0.654536  0.440953  0.137086  1.155270
1274 -0.165084  0.907545 -1.051983  1.222830  0.948567  1.492722 -0.290754
2891 -0.579277  0.318855  0.276370 -0.411698  0.580633  1.858734  0.677703

            X1        X0
1107  3.069596  1.984833
1468  0.167195  0.234812
123   1.545630 -0.318047
523  -1.570886 -0.397793
4566  0.831990 -0.144920
...        ...       ...
4681  0.788349  0.246560
3369 -0.115708  1.480462
4280  0.440953  1.155270
1274  0.948567 -0.290754
2891  0.580633  0.677703

[5000 rows x 9 columns], 'y': 1107    24.958725
1468     3.312083
123      8.510411
523     -0.942021
4566    12.538854
          ...
4681    -9.753915
3369    28.251476
4280    11.803582
1274     8.772153
2891    17.771505
Name: y, Length: 5000, dtype: float64, 'treatment': 1107     True
1468     True
123      True
523     False
4566     True
        ...
4681    False
3369     True
4280     True
1274    False
2891     True
Name: v0, Length: 5000, dtype: bool}
{'X':             W2        W4        W3        W1        X1        W0        X0  \
2726 -0.368195  0.254780 -1.386007 -0.019295  3.981678  1.721587  0.899386
2912 -0.764881 -1.102140  1.428223 -1.508671  2.435032  1.480412  0.523325
3987 -0.580005  1.195455  1.770907 -1.252660  0.783794  1.648682  0.839879
2547  0.189121 -0.637653 -0.910387 -1.400388  0.801744 -0.336660 -1.863484
1033 -0.157821 -0.844584  0.362423  0.386181  0.664080  0.114542  0.583622
...        ...       ...       ...       ...       ...       ...       ...
1956 -1.444609 -0.520487 -0.436115 -0.594927 -1.035937  1.144816  1.024175
3091 -0.996752 -1.001645  0.057433 -0.608571 -0.149226  0.630850  0.334182
707  -1.000939  0.607256 -1.361936 -1.114522 -0.518781  1.013982  1.163680
2777 -0.751750  1.124063 -0.855433 -0.128689 -0.059794  1.771620  0.386780
2739 -1.863242  0.967146  0.637419 -1.578002  2.430646  0.750446  0.499411

            X1        X0
2726  3.981678  0.899386
2912  2.435032  0.523325
3987  0.783794  0.839879
2547  0.801744 -1.863484
1033  0.664080  0.583622
...        ...       ...
1956 -1.035937  1.024175
3091 -0.149226  0.334182
707  -0.518781  1.163680
2777 -0.059794  0.386780
2739  2.430646  0.499411

[5000 rows x 9 columns], 'y': 2726    22.112912
2912    10.807143
3987    15.143257
2547    -8.830940
1033    14.263044
          ...
1956    10.565387
3091     6.726781
707     -3.424906
2777    15.153180
2739    12.643196
Name: y, Length: 5000, dtype: float64, 'treatment': 2726     True
2912     True
3987     True
2547    False
1033     True
        ...
1956     True
3091     True

## Refutation Values

In [14]:
refuter_count = 1
if inspect_refutations is True:
    for refutation in refutation_list:
        print("####### Refutation {}#######################################################################################".format(refuter_count))
        print("*** Class Name ***")
        print()
        print(refutation.refutation_type)
        print()
        print(refutation)
        print("########################################################################################################")
        print()
        refuter_count += 1

####### Refutation 1#######################################################################################
*** Class Name ***

Refute: Bootstrap Sample Dataset

Refute: Bootstrap Sample Dataset
Estimated effect:13.879166147783451
New effect:13.953445971526296
p value:0.38

########################################################################################################

####### Refutation 2#######################################################################################
*** Class Name ***

Refute: Use a subset of data

Refute: Use a subset of data
Estimated effect:13.879166147783451
New effect:13.840281043290043
p value:0.4

########################################################################################################

####### Refutation 3#######################################################################################
*** Class Name ***

Refute: Bootstrap Sample Dataset

Refute: Bootstrap Sample Dataset
Estimated effect:14.961425818165385
New effect:14.97968038230834
p value:0.45

########################################################################################################

####### Refutation 4#######################################################################################
*** Class Name ***

Refute: Use a subset of data

Refute: Use a subset of data
Estimated effect:14.961425818165385
New effect:14.958964391459405
p value:0.43999999999999995

########################################################################################################

####### Refutation 5#######################################################################################
*** Class Name ***

Refute: Bootstrap Sample Dataset

Refute: Bootstrap Sample Dataset
Estimated effect:[12.82779527]
New effect:12.896648276804534
p value:[0.3]

########################################################################################################

####### Refutation 6#######################################################################################
*** Class Name ***

Refute: Use a subset of data

Refute: Use a subset of data
Estimated effect:[12.82779527]
New effect:12.827589459953945
p value:[0.48]

########################################################################################################